apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # NEW: Application name
  name: course-service-institution-a
  namespace: argocd
spec:
  project: default
  source:
    # NEW: Points to the course-service Helm chart
    repoURL: 'https://github.com/HariomKhaladkar/edtech-app-code.git'
    path: course-service/chart
    targetRevision: main
    helm:
      values: |
        image:
          # This will be updated automatically by our new CI job
          tag: "0722ff92254e023d550e6e85c6ada01e9851db06"
  destination:
    server: 'https://kubernetes.default.svc'
    # We'll deploy it to the same namespace for simplicity
    namespace: institution-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
