apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-institution-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HariomKhaladkar/edtech-app-code.git'
    path: user-service
    targetRevision: main
    helm:
      values: |
        image:
          tag: "748b78eb143c0ab1fd8fd116eb62b76665f9ed6a"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: institution-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true